from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


REQUIRED_SPEC_KEYS = [
    "runner_type",
    "task_type",
    "dataset_url",
    "dataset_urls",
    "dataset_name",
    "target_column",
    "feature_columns",
    "baseline",
    "success_metric",
    "success_threshold",
    "threshold_direction",
    "notes_for_experiment_agent",
]


def section_text(text: str, heading: str) -> str:
    lines = text.splitlines()
    wanted = heading.strip().upper()
    start = None
    for index, line in enumerate(lines):
        if line.strip().upper() == wanted:
            start = index + 1
            break
    if start is None:
        return ""

    collected = []
    for line in lines[start:]:
        stripped = line.strip()
        if re.match(r"^[A-Z][A-Z\s]+:\s*$", stripped):
            break
        collected.append(line)
    return "\n".join(collected).strip()


def normalize_spec(spec: dict) -> dict:
    normalized = dict(spec or {})
    defaults = {
        "runner_type": "NEEDS_NEW_RUNNER",
        "task_type": "TO_VERIFY",
        "dataset_url": "TO_VERIFY",
        "dataset_urls": ["TO_VERIFY"],
        "dataset_name": "TO_VERIFY",
        "target_column": "TO_VERIFY",
        "feature_columns": ["TO_VERIFY"],
        "baseline": "TO_VERIFY",
        "success_metric": "TO_VERIFY",
        "success_threshold": 0.0,
        "threshold_direction": "TO_VERIFY",
        "notes_for_experiment_agent": "Generated by final_agent_prop.",
    }
    for key, value in defaults.items():
        if key not in normalized or normalized[key] in ("", None):
            normalized[key] = value
    if not isinstance(normalized.get("dataset_urls"), list):
        normalized["dataset_urls"] = [str(normalized.get("dataset_urls"))]
    if not isinstance(normalized.get("feature_columns"), list):
        normalized["feature_columns"] = [str(normalized.get("feature_columns"))]
    return {key: normalized[key] for key in REQUIRED_SPEC_KEYS}


def format_public_data_sources(dataset_report: dict, schema_report: dict) -> str:
    candidates = dataset_report.get("dataset_candidates", [])
    if not candidates:
        return "- TO_VERIFY: No readable direct dataset files were found automatically."

    schema_targets = []
    for schema in schema_report.get("schemas", []):
        targets = schema.get("target_candidates") or []
        if targets:
            schema_targets.extend(str(item) for item in targets)
    target_note = f" Candidate target columns from schema inspection: {', '.join(dict.fromkeys(schema_targets))}." if schema_targets else ""

    lines = []
    for candidate in candidates[:5]:
        direct_urls = [item.get("url") for item in candidate.get("direct_files", []) if item.get("url")]
        lines.append(
            "- "
            + f"{candidate.get('name', 'Dataset candidate')}: "
            + f"{candidate.get('description') or 'Readable public data files were found.'} "
            + f"Direct files: {', '.join(direct_urls[:5])}."
            + target_note
        )
    return "\n".join(lines)


def run_final_agent_prop(
    research_question: str,
    hypothesis_output: str,
    dataset_report: dict,
    schema_report: dict,
    analysis_spec: dict,
) -> str:
    hypothesis = section_text(hypothesis_output, "HYPOTHESIS:") or "TO_VERIFY"
    analysis_goal = section_text(hypothesis_output, "ANALYSIS GOAL:") or "Analyze public dataset files relevant to the research question."
    key_variables = section_text(hypothesis_output, "KEY VARIABLES:") or "- Independent variables: TO_VERIFY\n- Dependent variables: TO_VERIFY\n- Control variables: TO_VERIFY"
    success_criteria = section_text(hypothesis_output, "SUCCESS CRITERIA:") or "- Data source is public and reproducible.\n- Target variable and metric are explicit."
    spec = normalize_spec(analysis_spec)
    spec_text = json.dumps(spec, indent=2)

    return f"""RESEARCH QUESTION:
{research_question}

HYPOTHESIS:
{hypothesis}

EXPERIMENT DESIGN:
{analysis_goal}

PUBLIC DATA SOURCES:
{format_public_data_sources(dataset_report, schema_report)}

DATA COLLECTION PLAN:
The Dataset Agent searched for readable public files and discarded repositories, pages, model artifacts, config files, and unreadable URLs. The Schema Agent inspected the selected direct files when possible. The Experiment Agent should use only the direct dataset URLs in the execution spec.

METHODOLOGY:
Use the selected public data files, schema-inspected target candidates, and the runner specified in EXPERIMENT EXECUTION SPEC. If the target column is AUTO_TARGET or TO_VERIFY, the Experiment Agent may infer a target from loaded tabular data and report that inference in the results.

KEY VARIABLES:
{key_variables}

SUCCESS CRITERIA:
{success_criteria}

FEASIBILITY CHECK:
The analysis is feasible only to the extent that the listed direct files are readable and contain columns relevant to the hypothesis. If the execution spec uses NEEDS_NEW_RUNNER, the current Experiment Agent should inspect any readable files and report why the full analysis cannot run.

LIMITATIONS AND RISKS:
- Dataset search may miss sources that require credentials or manual download.
- Schema inference can select an imperfect target column when metadata is weak.
- A simple baseline runner cannot replace custom feature engineering, scraping, deep learning, causal inference, or multimodal processing.

EXPERIMENT EXECUTION SPEC:
{spec_text}
"""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Assemble final proposal from proposal subagent outputs.")
    parser.add_argument("--research-question", required=True)
    parser.add_argument("--hypothesis", required=True)
    parser.add_argument("--dataset-report", required=True)
    parser.add_argument("--schema-report", required=True)
    parser.add_argument("--analysis-spec", required=True)
    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()
    print(
        run_final_agent_prop(
            args.research_question,
            Path(args.hypothesis).read_text(encoding="utf-8"),
            json.loads(Path(args.dataset_report).read_text(encoding="utf-8")),
            json.loads(Path(args.schema_report).read_text(encoding="utf-8")),
            json.loads(Path(args.analysis_spec).read_text(encoding="utf-8")),
        )
    )
