import React, { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";

function parseQuestions(litOutput) {
  const questions = [];
  let inQuestionsSection = false;

  for (const line of litOutput.splitlines ? litOutput.split("\n") : []) {
    const trimmed = line.trim();

    if (trimmed.toUpperCase().includes("CANDIDATE RESEARCH QUESTIONS")) {
      inQuestionsSection = true;
      continue;
    }

    if (inQuestionsSection && trimmed && /^\d+\./.test(trimmed)) {
      let q = trimmed.replace(/^\d+\.\s*/, "");
      if (q.includes("| Gap addressed:")) {
        q = q.split("| Gap addressed:")[0].trim();
      }
      if (q.length > 10) {
        questions.push(q);
      }
    }
  }

  return questions;
}

export default function ResearchQuestionPage({ autonomous, litOutput, onComplete }) {
  const navigate = useNavigate();
  const [questions, setQuestions] = useState([]);
  const [selected, setSelected] = useState("");
  const [custom, setCustom] = useState("");
  const [useCustom, setUseCustom] = useState(false);

  console.log("litOutput received:", litOutput);
  
  useEffect(() => {
    if (litOutput) {
      const parsed = parseQuestions(litOutput);
      setQuestions(parsed);
    }
  }, [litOutput]);

  function handleConfirm() {
    const finalQuestion = useCustom ? custom.trim() : selected;
    if (!finalQuestion) return;
    onComplete(finalQuestion);
    navigate("/deep-literature");
  }

  const finalQuestion = useCustom ? custom.trim() : selected;

  return (
    <div className="stage-page">
      <h1>Research Question</h1>
      <p>Select a research question generated by the literature agent, or type your own.</p>

      {!litOutput && (
        <div className="warning-box">
          No literature output found. Please run the Literature stage first.
        </div>
      )}

      {litOutput && (
        <>
          {questions.length > 0 && !useCustom && (
            <div className="question-list">
              {questions.map((q, i) => (
                <div
                  key={i}
                  className={`question-item ${selected === q ? "selected" : ""}`}
                  onClick={() => setSelected(q)}
                >
                  {i + 1}. {q}
                </div>
              ))}
            </div>
          )}

          <div className="custom-question">
            <label>
              <input
                type="checkbox"
                checked={useCustom}
                onChange={() => {
                  setUseCustom(!useCustom);
                  setSelected("");
                }}
              />
              {" "}Enter my own research question
            </label>

            {useCustom && (
              <input
                className="topic-input"
                style={{ marginTop: "12px", width: "100%" }}
                type="text"
                placeholder="Type your research question..."
                value={custom}
                onChange={(e) => setCustom(e.target.value)}
              />
            )}
          </div>

          {finalQuestion && (
            <div className="selected-preview">
              <strong>Selected:</strong> {finalQuestion}
            </div>
          )}

          <button
            className="start-button"
            style={{ marginTop: "16px" }}
            onClick={handleConfirm}
            disabled={!finalQuestion}
          >
            Confirm & Continue to Deep Literature →
          </button>
        </>
      )}
    </div>
  );
}