import React, { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";

function parseQuestions(output) {
  const questions = [];
  let inSection = false;

  for (const line of output.split("\n")) {
    const trimmed = line.trim();

    if (trimmed.toUpperCase().includes("CANDIDATE RESEARCH QUESTIONS")) {
      inSection = true;
      continue;
    }

    if (inSection && trimmed && /^\d+\./.test(trimmed)) {
      let q = trimmed.replace(/^\d+\.\s*/, "");
      if (q.includes("| Gap addressed:")) {
        q = q.split("| Gap addressed:")[0].trim();
      }
      if (q.includes("| Feasibility:")) {
        q = q.split("| Feasibility:")[0].trim();
      }
      if (q.length > 30) {
        questions.push(q);
      }
    }
  }
  return questions;
}

export default function ResearchQuestionPage({ autonomous, topic, litOutput, onComplete }) {
  const navigate = useNavigate();
  const [questions, setQuestions] = useState([]);
  const [selected, setSelected] = useState("");
  const [custom, setCustom] = useState("");
  const [useCustom, setUseCustom] = useState(false);
  const [loading, setLoading] = useState(false);
  const [ready, setReady] = useState(false);
  const [error, setError] = useState("");

  useEffect(() => {
    if (litOutput && topic) {
      generateQuestions();
    }
  }, [litOutput, topic]);

  async function generateQuestions() {
    setLoading(true);
    setError("");
    setReady(false);
    setQuestions([]);

    try {
      const response = await fetch("http://localhost:8000/api/stages/research_questions/run", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          topic: topic,
          literature: litOutput
        })
      });

      if (!response.ok) {
        throw new Error(`Server error: ${response.status}`);
      }

      const data = await response.json();
      const parsed = parseQuestions(data.output || "");
      setQuestions(parsed);
      setReady(true);
    } catch (err) {
      setError(`Something went wrong: ${err.message}`);
    } finally {
      setLoading(false);
    }
  }

  function handleConfirm() {
    const finalQuestion = useCustom ? custom.trim() : selected;
    if (!finalQuestion) return;
    onComplete(finalQuestion);
    navigate("/deep-literature");
  }

  const finalQuestion = useCustom ? custom.trim() : selected;

  return (
    <div className="stage-page">
      <h1>Research Question</h1>
      <p>Select a research question generated by the literature agent, or type your own.</p>

      {!litOutput && (
        <div className="warning-box">
          No literature output found. Please run the Topic & Literature stage first.
        </div>
      )}

      {loading && (
        <div className="status-indicator">
          <div className="spinner"></div>
          <p>Generating research questions...</p>
        </div>
      )}

      {error && (
        <div className="warning-box">{error}</div>
      )}

      {ready && !useCustom && (
        <div className="question-list">
          {questions.map((q, i) => (
            <div
              key={i}
              className={`question-item ${selected === q ? "selected" : ""}`}
              onClick={() => setSelected(q)}
            >
              {i + 1}. {q}
            </div>
          ))}
        </div>
      )}

      {ready && (
        <div className="custom-question">
          <label>
            <input
              type="checkbox"
              checked={useCustom}
              onChange={() => {
                setUseCustom(!useCustom);
                setSelected("");
              }}
            />
            {" "}Enter my own research question
          </label>

          {useCustom && (
            <input
              className="topic-input"
              style={{ marginTop: "12px", width: "100%" }}
              type="text"
              placeholder="Type your research question..."
              value={custom}
              onChange={(e) => setCustom(e.target.value)}
            />
          )}
        </div>
      )}

      {finalQuestion && (
        <div className="selected-preview">
          <strong>Selected:</strong> {finalQuestion}
        </div>
      )}

      {ready && (
        <button
          className="start-button"
          style={{ marginTop: "16px" }}
          onClick={handleConfirm}
          disabled={!finalQuestion}
        >
          Confirm & Continue to Deep Literature →
        </button>
      )}
    </div>
  );
}