from __future__ import annotations

import argparse
import json
from pathlib import Path

try:
    from ..agent_api import call_agent_api
    from ..config import ANALYSIS_PRINCIPAL_ID
except ImportError:
    from agent_api import call_agent_api
    from config import ANALYSIS_PRINCIPAL_ID


ANALYSIS_PROMPT = """
You are the Analysis Agent in an autonomous research pipeline.

Input:
- Hypothesis Agent output
- Dataset Agent output
- Schema Agent output

Job:
Create the final executable EXPERIMENT EXECUTION SPEC for the Experiment Agent.

Rules:
- Only use direct dataset URLs listed by the Dataset Agent.
- Prefer columns inspected by the Schema Agent.
- If a target candidate exists, choose the best target column.
- If rows loaded but no target candidate exists, use AUTO_TARGET.
- If no readable files loaded or the data cannot answer the hypothesis, use NEEDS_NEW_RUNNER.
- Do not invent URLs, columns, metrics, datasets, or results.
- Output one valid JSON object only.

Required JSON keys:
runner_type, task_type, dataset_url, dataset_urls, dataset_name, target_column,
feature_columns, baseline, success_metric, success_threshold, threshold_direction,
notes_for_experiment_agent.
"""


def extract_json_object(text: str) -> dict | None:
    start = text.find("{")
    if start == -1:
        return None
    depth = 0
    in_string = False
    escape = False
    for index in range(start, len(text)):
        char = text[index]
        if escape:
            escape = False
            continue
        if char == "\\":
            escape = True
            continue
        if char == '"':
            in_string = not in_string
            continue
        if in_string:
            continue
        if char == "{":
            depth += 1
        elif char == "}":
            depth -= 1
            if depth == 0:
                return json.loads(text[start : index + 1])
    return None


def dataset_urls(dataset_report: dict, limit: int = 5) -> list[str]:
    urls = []
    for candidate in dataset_report.get("dataset_candidates", []):
        for item in candidate.get("direct_files", []):
            url = item.get("url", "")
            if url:
                urls.append(url)
            if len(urls) >= limit:
                return list(dict.fromkeys(urls))
    return list(dict.fromkeys(urls))


def first_target_candidate(schema_report: dict) -> str:
    for schema in schema_report.get("schemas", []):
        candidates = schema.get("target_candidates") or []
        if candidates:
            return str(candidates[0])
    return "AUTO_TARGET" if schema_report.get("rows_loaded", 0) else "TO_VERIFY"


def fallback_analysis_spec(dataset_report: dict, schema_report: dict, reason: str) -> dict:
    urls = dataset_urls(dataset_report)
    if not urls:
        return {
            "runner_type": "NEEDS_NEW_RUNNER",
            "task_type": "TO_VERIFY",
            "dataset_url": "TO_VERIFY",
            "dataset_urls": ["TO_VERIFY"],
            "dataset_name": "TO_VERIFY",
            "target_column": "TO_VERIFY",
            "feature_columns": ["TO_VERIFY"],
            "baseline": "TO_VERIFY",
            "success_metric": "TO_VERIFY",
            "success_threshold": 0.0,
            "threshold_direction": "TO_VERIFY",
            "notes_for_experiment_agent": f"No executable dataset files were found. Reason: {reason}",
        }

    all_csv = all(url.lower().split("?", 1)[0].endswith(".csv") for url in urls)
    target_column = first_target_candidate(schema_report)
    has_loaded_rows = bool(schema_report.get("rows_loaded", 0))
    can_attempt_baseline = all_csv or has_loaded_rows
    return {
        "runner_type": "universal_tabular_csv" if all_csv else "universal_data_file",
        "task_type": "auto" if can_attempt_baseline else "inspect",
        "dataset_url": urls[0],
        "dataset_urls": urls,
        "dataset_name": "dataset_agent_candidates",
        "target_column": target_column if can_attempt_baseline else "TO_VERIFY",
        "feature_columns": ["AUTO_NUMERIC"],
        "baseline": "majority_class for classification or mean_prediction for regression",
        "success_metric": "accuracy" if can_attempt_baseline else "inspect",
        "success_threshold": 0.0,
        "threshold_direction": "greater_or_equal",
        "notes_for_experiment_agent": f"Generated by Analysis Agent fallback. Reason: {reason}",
    }


def run_analysis_agent(hypothesis_output: str, dataset_report: dict, schema_report: dict) -> dict:
    prompt = f"""{ANALYSIS_PROMPT}

Hypothesis Agent output:
{hypothesis_output}

Dataset Agent output:
{json.dumps(dataset_report, indent=2)}

Schema Agent output:
{json.dumps(schema_report, indent=2)}
"""
    try:
        raw = call_agent_api(prompt, "Analysis", ANALYSIS_PRINCIPAL_ID)
        parsed = extract_json_object(raw)
        if isinstance(parsed, dict):
            return parsed
        return fallback_analysis_spec(dataset_report, schema_report, "Analysis Agent did not return valid JSON.")
    except Exception as exc:
        print(f"Analysis failed; using fallback. Reason: {exc}")
        return fallback_analysis_spec(dataset_report, schema_report, str(exc))


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Create experiment execution spec from proposal subagent outputs.")
    parser.add_argument("--hypothesis", required=True)
    parser.add_argument("--dataset-report", required=True)
    parser.add_argument("--schema-report", required=True)
    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()
    hypothesis = Path(args.hypothesis).read_text(encoding="utf-8")
    dataset_report = json.loads(Path(args.dataset_report).read_text(encoding="utf-8"))
    schema_report = json.loads(Path(args.schema_report).read_text(encoding="utf-8"))
    print(json.dumps(run_analysis_agent(hypothesis, dataset_report, schema_report), indent=2))
